name: Check for Large Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-large-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find files over 25MB
        run: |
          # Search for files larger than 25MB and print their paths
          large_files=$(find . -type f -size +25M)
          if [ -n "$large_files" ]; then
            echo "Large file(s) detected:"
            echo "$large_files"
            exit 1
          else
            echo "No large files found"
          fi

